//  ViewController.swift
//  Source used: https://github.com/appcoda/FullScreenCamera

//  Description: Camera Controller for Photo Mode

//  CMPT 275 Group 3 - SavePark
//  Fall 2018

//  File Created By: Curtis Cheung
//  File Modified By: Curtis Cheung

//  All changes are marked with "CMPT275" (no quotes)
//  Changes:
//  10/19/2018 - Added HVAA Button placeholder
//  10/25/2018 - Code Cleanup (comments), Added View transition to ProcessPhotos
//  10/25/2018 - Added Photo Instruction Alert (Placeholder), Added Back button (in Storyboard)
//  10/25/2018 - Added Alert Dialog when Camera is not detected
//  10/27/2018 - Shutter button can now be only pressed once to avoid multiple function calls,
//               Added Error Handling when saving photos


import UIKit
import Photos
import CoreMotion

var cameraDetected = true;

class ViewController: UIViewController {
    
    @IBOutlet weak var captureButton: UIButton!
    //@IBOutlet fileprivate var captureButton: UIButton!
    
    ///Displays a preview of the video output generated by the device's cameras.
    @IBOutlet fileprivate var capturePreviewView: UIView!
    
    ///Allows the user to put the camera in photo mode.
    @IBOutlet fileprivate var photoModeButton: UIButton!
    @IBOutlet fileprivate var toggleCameraButton: UIButton!
    @IBOutlet fileprivate var toggleFlashButton: UIButton!
    
    let cameraController = CameraController()
    
    // CMPT275 - Alias for Core Motion Library (Accelerometer / Gyroscope)
    let motion = CMMotionManager()
    
    override var prefersStatusBarHidden: Bool { return true }
    
    // CMPT 275 - Photo Mode Instructions Alert
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        if (cameraDetected == true)
        {
            let alertController = UIAlertController(title: "Instructions", message: "Photo Mode Instructions", preferredStyle: .alert)
            alertController.addAction(UIAlertAction(title: "OK", style: .cancel, handler: nil))
            present(alertController, animated: true, completion: nil)
        }
        else
        {
            let alertController = UIAlertController(title: "Error", message: "No Camera Detected", preferredStyle: .alert)
            alertController.addAction(UIAlertAction(title: "OK", style: .cancel, handler: nil))
            present(alertController, animated: true, completion: nil)
        }

    }
    
}

extension ViewController {
    override func viewDidLoad() {
        
        
        func configureCameraController() {
            cameraController.prepare {(error) in
                if let error = error {
                    print(error)
                    cameraDetected = false;
                    self.dismiss(animated: true)
                }
                try? self.cameraController.displayPreview(on: self.capturePreviewView)
            }
        }
        
        func styleCaptureButton() {
            captureButton.layer.borderColor = UIColor.black.cgColor
            captureButton.layer.borderWidth = 2
            
            captureButton.layer.cornerRadius = min(captureButton.frame.width, captureButton.frame.height) / 2
        }
        
        styleCaptureButton()
        configureCameraController()
    
    }
}

extension ViewController {
    @IBAction func toggleFlash(_ sender: UIButton) {
        if cameraController.flashMode == .on {
            cameraController.flashMode = .off
            toggleFlashButton.setImage(#imageLiteral(resourceName: "Flash Off Icon"), for: .normal)
        }
            
        else {
            cameraController.flashMode = .on
            toggleFlashButton.setImage(#imageLiteral(resourceName: "Flash On Icon"), for: .normal)
        }
    }
    
    // CMPT275 - HVAA Feature
    @IBAction func HVAA_toggle(_ sender: UIButton) {
        NSLog("Works")
    }
    
    @IBAction func switchCameras(_ sender: UIButton) {
        do {
            try cameraController.switchCameras()
        }
            
        catch {
            print(error)
        }
        
        switch cameraController.currentCameraPosition {
        case .some(.front):
            toggleCameraButton.setImage(#imageLiteral(resourceName: "Front Camera Icon"), for: .normal)
            
        case .some(.rear):
            toggleCameraButton.setImage(#imageLiteral(resourceName: "Rear Camera Icon"), for: .normal)
            
        case .none:
            return
        }
    }
    
    @IBAction func captureImage(_ sender: UIButton) {
        // CMPT 275 - Disable button after single button
        (sender as? UIButton)?.isEnabled = false
        cameraController.captureImage {(image, error) in
            guard let image = image else {
                print(error ?? "Image capture error")
                return
            }
                PHPhotoLibrary.shared().performChanges({
                    PHAssetChangeRequest.creationRequestForAsset(from: image)
                }, completionHandler: { success, error in
                    if success {
                        NSLog("Saved Photo")
                    } else {
                        NSLog("Failed Saving Photo")
                    }
                })
        }
        // CMPT275 - Present Process Photos View Controller after capturing photos
        let viewController = self.storyboard?.instantiateViewController(withIdentifier: "processphotos") as! UIViewController
        self.present(viewController, animated: true)
        (sender as? UIButton)?.isEnabled = true;
        }

    }

